# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('stop', models.TimeField(blank=True, null=True)),
                ('distance', models.FloatField()),
                ('measurement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardioInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_start', models.TimeField(blank=True, null=True)),
                ('action_stop', models.TimeField(blank=True, null=True)),
                ('rest_start', models.TimeField(blank=True, null=True)),
                ('rest_stop', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardioRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('stop', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardioScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_part', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('shoulder', 'Shoulder'), ('core', 'Core')], max_length=50)),
                ('modality', models.CharField(choices=[('barbell', 'Barbell'), ('kettlebell', 'Kettlebell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('smith', 'Smith'), ('band', 'Band'), ('body-weight', 'Body Weight')], help_text='Method of exercise', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rep_style', models.CharField(choices=[('str', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('power', 'Power'), ('endurance', 'Endurance')], max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('load', models.IntegerField(help_text='Weight in pounds')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_set', to='fitness.ResistanceScheme')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='resistancescheme',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_scheme', to='fitness.Workout'),
        ),
        migrations.AddField(
            model_name='cardioscheme',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Exercise'),
        ),
        migrations.AddField(
            model_name='cardioscheme',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_scheme', to='fitness.Workout'),
        ),
        migrations.AddField(
            model_name='cardiorepetition',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetition_set', to='fitness.CardioScheme'),
        ),
        migrations.AddField(
            model_name='cardiointerval',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_set', to='fitness.CardioScheme'),
        ),
        migrations.AddField(
            model_name='cardiodistance',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_set', to='fitness.CardioScheme'),
        ),
    ]
