# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistancescheme',
            name='rep_style',
            field=models.CharField(blank=True, choices=[('str', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('power', 'Power'), ('endurance', 'Endurance')], max_length=20, null=True),
        ),
    ]
