# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20170714_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('modality', models.CharField(help_text='Method of cardio', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cardioscheme',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.CardioExercise'),
        ),
    ]
