# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20170622_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutSet',
            new_name='ResistanceScheme',
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date']},
        ),
    ]
