# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20170715_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardioexercise',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='modality',
        ),
        migrations.AddField(
            model_name='cardioscheme',
            name='modality',
            field=models.CharField(blank=True, help_text='Method of cardio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resistancescheme',
            name='modality',
            field=models.CharField(blank=True, choices=[('barbell', 'Barbell'), ('kettlebell', 'Kettlebell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('smith', 'Smith'), ('band', 'Band'), ('body-weight', 'Body Weight')], help_text='Method of exercise', max_length=50, null=True),
        ),
    ]
