# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20170701_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiodistance',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_set', to='fitness.CardioScheme'),
        ),
        migrations.AlterField(
            model_name='cardiointerval',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_set', to='fitness.CardioScheme'),
        ),
        migrations.AlterField(
            model_name='cardiorepetition',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetition_set', to='fitness.CardioScheme'),
        ),
        migrations.AlterField(
            model_name='cardioscheme',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_scheme', to='fitness.Workout'),
        ),
        migrations.AlterField(
            model_name='resistancescheme',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_scheme', to='fitness.Workout'),
        ),
        migrations.AlterField(
            model_name='resistanceset',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_set', to='fitness.ResistanceScheme'),
        ),
    ]
