# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20170715_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiointerval',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
