# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20170701_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='resistanceset',
            name='other_scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resistance_other', to='fitness.ResistanceScheme'),
            preserve_default=False,
        ),
    ]
