# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20170701_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resistanceset',
            name='intensity',
            field=models.FloatField(),
        ),
    ]
